### ISSUE TITLE
Problem with installing in Termux

### ISSUE THREAD

**Issue by silentShodow** [creotiv/MiBand2#27]
Traceback (most recent call last):
  File "example.py", line 5, in <module>
    from base import MiBand2
  File "/data/data/com.termux/files/home/MiBand2/base.py", line 5, in <module>
    from Crypto.Cipher import AES
ModuleNotFoundError: No module named 'Crypto'

Sorry if my question is stupid 

I write in Termux "pkg install pycrypto" but it's don't work

Help me please :)

**Comment by apnof** [comment]
Does 
pkg install libcrypt-dev
help?

**Comment by silentShodow** [comment]
Doesn't work

**Comment by silentShodow** [comment]
New problem. Bluepy)0)

**Comment by silentShodow** [comment]
Thanks)

**Comment by noob6t5** [comment]
I'm also having same problems how to solve?
