### ISSUE TITLE
I can not connect to my miband 2

### ISSUE THREAD

**Issue by JoaoNeto99** [creotiv/MiBand2#29]
Hello, how are you? I'm having trouble connecting to my miband 2. I get this error right after I use it python example.py --mac F3:77:1A:30:11:BB --init can you help me?

2019-07-14 19:58:08,024 MiBand2 (INFO) > Connecting to F3:77:1A:30:11:BB
Traceback (most recent call last):
  File "example.py", line 18, in <module>
    band = MiBand2(MAC, debug=True)
  File "/media/joao/ae7aaea4-b12b-4927-9747-e801a8106f15/joao/Área de Trabalho/Pasta sem título/MiBand2-master/base.py", line 134, in __init__
    Peripheral.__init__(self, mac_address, addrType=ADDR_TYPE_RANDOM)
  File "/usr/local/lib/python2.7/dist-packages/bluepy/btle.py", line 391, in __init__
    self._connect(deviceAddr, addrType, iface)
  File "/usr/local/lib/python2.7/dist-packages/bluepy/btle.py", line 439, in _connect
    raise BTLEDisconnectError("Failed to connect to peripheral %s, addr type: %s" % (addr, addrType), rsp)
bluepy.btle.BTLEDisconnectError: Failed to connect to peripheral F3:77:1A:30:11:BB, addr type: random

**Comment by franalotto94** [comment]
Hello,

Try to reset Bluetooth harware by typing on terminal:
`sudo hciconfig hci0 reset`


Sincerely,
Francesco
