### ISSUE TITLE
python example.py --mac MAC_ADDRESS --init

### ISSUE THREAD

**Issue by jalpeshpanchal99** [creotiv/MiBand2#41]
Traceback (most recent call last):
  File "example.py", line 5, in <module>
    from base import MiBand2
  File "/root/MiBand2/base.py", line 104
    self.device.outfile.write(f"{timestamp.strftime('%d.%m.%Y - %H:%M')},{category},{intensity},{steps},{heart_rate}\n")

**Comment by yeah61** [comment]
> Traceback (most recent call last):
> File "example.py", line 5, in
> from base import MiBand2
> File "/root/MiBand2/base.py", line 104
> self.device.outfile.write(f"{timestamp.strftime('%d.%m.%Y - %H:%M')},{category},{intensity},{steps},{heart_rate}\n")

have you solved this problem? I meet the same question today.

**Comment by GiacomoEandi** [comment]
I solved commenting the line 104 within the file base.py
Now it works with my Raspberry Pi 4
