### ISSUE TITLE
Example.py hangs after 'Connected'

### ISSUE THREAD

**Issue by nicholastps93** [creotiv/MiBand2#7]
After running example py, the (INFO) > Connected status hangs infinitely. Traceback after stopping is as below:

Traceback (most recent call last):
  File "example.py", line 8, in <module>
    band = MiBand2(MAC, debug=True)
  File "/home/pi/MiBand2/base.py", line 85, in __init__
    self.svc_1 = self.getServiceByUUID(UUIDS.SERVICE_MIBAND1)
  File "/usr/local/lib/python2.7/dist-packages/bluepy/btle.py", line 447, in getServiceByUUID
    rsp = self._getResp('find')
  File "/usr/local/lib/python2.7/dist-packages/bluepy/btle.py", line 369, in _getResp
    resp = self._waitResp(wantType + ['ntfy', 'ind'], timeout)
  File "/usr/local/lib/python2.7/dist-packages/bluepy/btle.py", line 312, in _waitResp
    rv = self._helper.stdout.readline()
KeyboardInterrupt
Exception IOError: (32, 'Broken pipe') in <bound method MiBand2.__del__ of <base.MiBand2 instance at 0x76be3440>> ignored

**Comment by creotiv** [comment]
Did you linked your band before run script to get info?
Bluetooth is turned on, and see the device?

**Comment by nicholastps93** [comment]
Yes the device is detected and after INFO > Connecting, the next line INFO > Connected appears. So it is likely that the connection is successful, but based on the traceback it seems like the bluepy library is waiting for a response. I saw a similar problem here (https://github.com/IanHarvey/bluepy/issues/167), it could be because the address type is supposed to be set as random?

**Comment by creotiv** [comment]
hm.. ok i will look at this.


Kindly yours,
Andrey Nikishaev

Sit&Fit <https://angel.co/sit-fit/> - underdesk stepper trainer.
Essenly <http://essenly.com> - книги в кратком изложении.
groovyCV <http://groovycv.com> - создание стильных резюме

Rates         Soft Dev from $40/h, Consultation BizDev/Marketing/Customer
Rel/IT from $80/h
LinkedIn      http://ua.linkedin.com/in/creotiv
GitHub        http://github.com/creotiv
Slideshare  https://www.slideshare.net/anikishaev/
Skype         creotiv.in.ua
Mobile        +380632410666
